---
- hosts: local
  connection: local
  sudo: yes
  sudo_user: "{{user}}"
  tasks:
    -
      name: Enumerate dotfile directories
      shell: cd dotfiles/{{user}} && find * -type d
      register: dotdirs
    -
      name: Create dotfile directories
      file: path="{{home}}/.{{item}}" mode=0700 state=directory recurse=true
      with_items: dotdirs.stdout_lines
    -
      name: Enumerate dotfiles
      shell: cd dotfiles/{{user}} && find * -type f
      register: dotfiles
    -
      name: Install dotfiles
      template: dest="{{home}}/.{{item|mandatory|regexp_replace('.enc$', '')}}" src="dotfiles/{{user}}/{{item}}" mode=0600
      with_items: dotfiles.stdout_lines
