---
- hosts: local
  connection: local
  sudo: yes
  sudo_user: "{{user}}"
  tasks:
    - name: Install emacs
      yum: name={{item}} state=present
      with_items:
        - emacs
        - emacs-color-theme-el
        - emacs-goodies
    - name: Configure emacs
      git: dest={{home}}/.emacs.d repo=git@github.com:{{user}}/dotemacs.git update=no
      notify: Install emacs packages
  handlers:
    - name: Install emacs packages
      shell: emacs --user {{user}} --batch --eval t
