---
- hosts: local
  connection: local
  sudo: yes
  sudo_user: "{{user}}"
  tasks:
    - file: path="{{home}}/.emacs.d" state=directory
    - copy: dest="{{home}}/.emacs.d/init.el" src=emacs/init.el
      notify: package refresh contents
  handlers:
    - name: package refresh contents
      shell: emacs --user sheldonh --batch --eval "(package-refresh-contents)"
- hosts: local
  connection: local
  sudo: yes
  sudo_user: "{{user}}"
  tasks:
    - elpa: pkg={{item}}
      with_items:
        - magit
        - yaml-mode
        - wrap-region
