---
- hosts: local
  connection: local
  tasks:
    - name: Install kerberos client
      yum: name=krb5-workstation state=present
    - name: Configure kerberos
      copy: dest=/etc/krb5.conf src=krb5.conf.enc
