---
- hosts: local
  connection: local
  sudo: yes
  sudo_user: "{{user}}"
  vars:
    confdir: "{{home}}/.kde/share/config"
    appdir: "{{home}}/.kde/share/apps/konsole"
  tasks:
    - name: Install Railscasts colorscheme into Konsole
      copy: dest={{appdir}}/Railscasts.colorscheme src=konsole/Railscasts.colorscheme
    - name: Create Railscasts profile for Konsole
      copy: dest={{appdir}}/Railscasts.profile src=konsole/Railscasts.profile
    - name: Set Railscasts as default Konsole profile
      ini_file: dest={{confdir}}/konsolerc section="Desktop Entry" option="DefaultProfile" value="Railscasts.profile"
