---
- hosts: local
  connection: local
  sudo: yes
  sudo_user: "{{user}}"
  tasks:
    - kconfig: file=konversationrc group=Flags key=HideUnimportantEvents value=true
    - kconfig: file=konversationrc group=Flags key=HideUnimportantEventsExcludeActive value=true
    - kconfig: file=konversationrc group="General Options" key=AutomaticRememberLine value=true
    - kconfig: file=konversationrc group="Identity 0" key=Name value="Default Identity"
    - kconfig: file=konversationrc group="Identity 0" key=Realname value="Sheldon Hearn"
    - kconfig: file=konversationrc group="Identity 0" key=Nicknames value=sheldonh,sheldonh_,sheldonh__
    - kconfig: file=konversationrc group="Identity 0" key=Ident value=sheldonh
    - kconfig: file=konversationrc group="Identity 0" key=Bot value=nickserv
    - name: Set Freenode password
      kconfig: file=konversationrc group="Identity 0" key=Password value="{{lookup('password', 'konversation.password.enc') }}"
    - kconfig: file=konversationrc group="Server 0" key=Server value="chat.freenode.net"
    - kconfig: file=konversationrc group="ServerGroup 0" key=Name value="Freenode"
    - kconfig: file=konversationrc group="ServerGroup 0" key=AutoConnect value=true
    - kconfig: file=konversationrc group="ServerGroup 0" key=AutoJoinChannels value=""
    - kconfig: file=konversationrc group="ServerGroup 0" key=Identity value=""
    - kconfig: file=konversationrc group="ServerGroup 0" key=ServerList value="Server 0"
    - kconfig: file=konversationrc group="Appearance" key=CustomTextFont value=true
    - kconfig: file=konversationrc group="Appearance" key=TextFont value="Sans Serif,16,-1,5,50,0,0,0,0,0"
